In [1]:
print("Hello Mission Mangal")

Hello Mission Mangal

In [ ]:
# Day - 16     4/10/2026
# print("Hello Mission Mangal") gathering data using json and sql

In [4]:
import pandas as pd

# working with json(java script on notation)

In [6]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# working with SQL

In [8]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     --- ------------------------------------ 1.0/11.9 MB 6.9 MB/s eta 0:00:02
     -------- ------------------------------- 2.6/11.9 MB 6.7 MB/s eta 0:00:02
     ---------- ----------------------------- 3.1/11.9 MB 6.8 MB/s eta 0:00:02
     --------------- ------------------------ 4.7/11.9 MB 6.0 MB/s eta 0:00:02
     -------------------- ------------------- 6.0/11.9 MB 6.1 MB/s eta 0:00:01
     ------------------------ --------------- 7.3/11.9 MB 6.2 MB/s eta 0:00:01
     ----------------------------- ---------- 8.7/11.9 MB 6.1 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 6.2 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 6.3 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 6.1 MB/s  0:00:02
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=b89147bb304bb836e268e19649f81005e4c2f53f82ef54556c7ded28d9ba13f5
  Stored in directory: c:\users\lucky\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import mysql.connector

In [15]:
conn = mysql.connector.connect(host = 'localhost',user ='root',password='',database='world')

In [17]:
pd.read_sql_query("select * from city where countrycode ='ind' ",conn)

C:\Users\lucky\AppData\Local\Temp\ipykernel_5648\3961972781.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from city where countrycode ='ind' ",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [18]:
git init

SyntaxError: invalid syntax (3277417328.py, line 1)